/**
 * Email Service for sending reports via email
 * Uses Nodemailer for email delivery
 */

const express = require('express');
const { createTransport } = require('nodemailer');
const cors = require('cors');
const bodyParser = require('body-parser');
require('dotenv').config();

const app = express();
const PORT = process.env.EMAIL_SERVICE_PORT || 5001;

// Middleware
app.use(cors());
app.use(bodyParser.json({ limit: '50mb' })); // Increased limit for large reports
app.use(bodyParser.urlencoded({ extended: true, limit: '50mb' }));

// Email configuration
const transporter = createTransport({
    service: process.env.EMAIL_SERVICE || 'gmail',
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASSWORD
    }
});

// Verify email configuration
transporter.verify((error, success) => {
    if (error) {
        console.log('❌ Email service error:', error);
    } else {
        console.log('✅ Email service ready');
    }
});

/**
 * Send email with report attachment
 */
app.post('/send-report', async (req, res) => {
    try {
        const { to_email, report_type, report_html, user_state, user_location } = req.body;

        if (!to_email) {
            return res.status(400).json({ error: 'Missing to_email field' });
        }

        if (!report_html) {
            return res.status(400).json({ error: 'Missing report_html field' });
        }

        const reportTypeName = report_type === 'eda' ? 'EDA Analysis' : 'Optimization';
        const timestamp = new Date().toISOString().replace(/:/g, '-').split('.')[0];
        const filename = `${report_type}_report_${timestamp}.html`;

        // Email subject
        let subject = `Inventory ${reportTypeName} Report`;
        if (user_location && user_state) {
            subject += ` - ${user_location}, ${user_state}`;
        }

        // Email body
        const emailBody = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #1976d2;">Inventory ${reportTypeName} Report</h2>
            <p>Hello,</p>
            <p>Your ${reportTypeName.toLowerCase()} report has been generated and is attached to this email.</p>
            ${user_location && user_state ? `<p><strong>Location:</strong> ${user_location}, ${user_state}</p>` : ''}
            <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
            <p>Please open the attached HTML file in your web browser to view the complete report with charts and visualizations.</p>
            <hr style="margin: 20px 0; border: none; border-top: 1px solid #ddd;">
            <p style="color: #757575; font-size: 12px;">
                This report was automatically generated by the Inventory Optimization System.<br>
                Hack Revolution 2025
            </p>
        </div>
        `;

        // Mail options
        const mailOptions = {
            from: `"Inventory Optimizer" <${process.env.EMAIL_USER}>`,
            to: to_email,
            subject: subject,
            html: emailBody,
            attachments: [
                {
                    filename: filename,
                    content: report_html,
                    contentType: 'text/html'
                }
            ]
        };

        // Send email
        const info = await transporter.sendMail(mailOptions);

        console.log(`✉️ Email sent: ${info.messageId}`);

        res.json({
            success: true,
            message: 'Report sent successfully',
            messageId: info.messageId,
            to: to_email,
            filename: filename
        });

    } catch (error) {
        console.error('Email error:', error);
        res.status(500).json({
            success: false,
            error: error.message
        });
    }
});

/**
 * Send simple email notification
 */
app.post('/send-notification', async (req, res) => {
    try {
        const { to_email, subject, message } = req.body;

        if (!to_email) {
            return res.status(400).json({ error: 'Missing to_email field' });
        }

        const emailBody = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <p>${message || 'You have a new notification from the Inventory Optimization System.'}</p>
            <hr style="margin: 20px 0; border: none; border-top: 1px solid #ddd;">
            <p style="color: #757575; font-size: 12px;">
                Inventory Optimization System | Hack Revolution 2025
            </p>
        </div>
        `;

        const mailOptions = {
            from: `"Inventory Optimizer" <${process.env.EMAIL_USER}>`,
            to: to_email,
            subject: subject || 'Inventory Notification',
            html: emailBody
        };

        const info = await transporter.sendMail(mailOptions);

        console.log(`✉️ Notification sent: ${info.messageId}`);

        res.json({
            success: true,
            message: 'Notification sent successfully',
            messageId: info.messageId,
            to: to_email
        });

    } catch (error) {
        console.error('Email error:', error);
        res.status(500).json({
            success: false,
            error: error.message
        });
    }
});

/**
 * Health check endpoint
 */
app.get('/health', (req, res) => {
    res.json({
        status: 'healthy',
        service: 'email',
        message: 'Email service is running',
        timestamp: new Date().toISOString()
    });
});

// Start server
app.listen(PORT, () => {
    console.log('='.repeat(60));
    console.log('📧 Email Service Starting...');
    console.log('='.repeat(60));
    console.log(`📍 Server URL: http://localhost:${PORT}`);
    console.log('\n📚 Available Endpoints:');
    console.log('  POST /send-report - Send report via email');
    console.log('  POST /send-notification - Send email notification');
    console.log('  GET  /health - Health check');
    console.log('='.repeat(60));
    console.log('\n✨ Server ready to send emails...');
});

module.exports = app;
